### ISSUE TITLE
error installing pysha3

### ISSUE THREAD

**Issue by rasyidred** [trailofbits/solc-select#125]
> Running setup.py install for pysha3 ... error
error: subprocess-exited-with-error
× Running setup.py install for pysha3 did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      running install
      C:\Users\Rasyid\AppData\Local\Programs\Python\Python311\Lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      copying sha3.py -> build\lib.win-amd64-cpython-311
      running build_ext
      building '_sha3' extension
      creating build\temp.win-amd64-cpython-311
      creating build\temp.win-amd64-cpython-311\Release
      creating build\temp.win-amd64-cpython-311\Release\Modules
      creating build\temp.win-amd64-cpython-311\Release\Modules\_sha3
      "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPY_WITH_KECCAK=1 -IC:\Users\Rasyid\AppData\Local\Programs\Python\Python311\include -IC:\Users\Rasyid\AppData\Local\Programs\Python\Python311\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.30.30705\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt" /TcModules/_sha3/sha3module.c /Fobuild\temp.win-amd64-cpython-311\Release\Modules/_sha3/sha3module.obj
      sha3module.c
      C:\Users\Rasyid\AppData\Local\Temp\pip-install-4cewblfa\pysha3_05127fc6155f46e7b8add9ce8b7b44ea\Modules\_sha3\backport.inc(78): fatal error C1083: Cannot open include file: 'pystrhex.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.30.30705\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure
× Encountered error while trying to install package.
╰─> pysha3
note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

I found this issue when installing the solc-select with pip and I also have a similar error message when installing the package with 
`git clone https://github.com/crytic/solc-select.git`
`cd solc-select`
`python3 setup.py install `

How should I do to fix this issue? Thank you!

**Comment by elopez** [comment]
It looks like this `pystrhex.h` header file that the `pysha3` dependency requires to build was removed in Python 3.11. You'll need to use Python 3.10 or earlier for the time being.

We have been wanting to remove the `pysha3` dependency across the crytic tools as the library is unmaintained, and this is a good reason to prioritize doing so, so I'm hoping this will not be an issue for long 👍

**Comment by rasyidred** [comment]
Thank you for the information! I just downgraded to python 3.9, and I could install solc-select successfully. I hope it will be fixed soon so that the latest Python can work with the solc-select 👍
