### ISSUE TITLE
solc -version

### ISSUE THREAD

**Issue by coderlrj** [trailofbits/solc-select#131]
After installed the solc-selecct by 'pip3 install solc-select', when I ran 'solc -version', there coming solc-select is out of date. Please run `solc-select upgrade‘. And when I ran 'solc-select upgrage', there coming 'solc-select is already up to date'

**Comment by ashokdv** [comment]
Pip version? 
Python Version?

**Comment by coderlrj** [comment]
solc --version

**Comment by elopez** [comment]
Closing this issue as it has not had activity for a while. If you are still experiencing issues on the latest release feel free to create a new issue.
