### ISSUE TITLE
install matches more versions than it should

### ISSUE THREAD

**Issue by 0xalpharush** [trailofbits/solc-select#142]
`solc-select use 0.8.17 --always-install`
Installing '0.8.17'...
Version '0.8.17' installed.
Installing '0.8.1'...
Version '0.8.1' installed.
Switched global version to 0.8.17
This line is wrong https://github.com/crytic/solc-select/blob/7b493c684aece2dc3e4f233fe044f23c1606be95/solc_select/solc_select.py#L77

**Comment by elopez** [comment]
Hi @0xalpharush, I tried and could not reproduce this here:

```sh
$ rm ~/.solc-select -rf
$ solc-select use 0.8.17 --always-install

Installing '0.8.17'...
Version '0.8.17' installed.
Switched global version to 0.8.17

```

I believe we fixed this some time ago: https://github.com/crytic/solc-select/pull/96

**Comment by 0xalpharush** [comment]
I must have not updated. Thanks!
