### ISSUE TITLE
`install artifacts` never returns false

### ISSUE THREAD

**Issue by 0xalpharush** [trailofbits/solc-select#143]
https://github.com/crytic/solc-select/blob/7b493c684aece2dc3e4f233fe044f23c1606be95/solc_select/solc_select.py#L72

**Comment by azpwnz** [comment]
Hi @0xalpharush ,
I would love to contribute to the repo.

Could you suggest in which cases `install_artifacts` should return `False`?
Would appreciate any details.

Thank you! :)

**Comment by 0xalpharush** [comment]
@azpwnz It should return `False` when installation of `versions` are unsuccessful. That is, when `get_available_versions` does not contain all of the `versions`.

**Comment by azpwnz** [comment]
@0xalpharush thank you for the explanation! 
I've prepared a PR with the changes https://github.com/crytic/solc-select/pull/151

**Comment by elopez** [comment]
Closing as this has been released in [v1.0.4](https://github.com/crytic/solc-select/releases/tag/v1.0.4). Thanks for the contribution @azpwnz !
