### ISSUE TITLE
[documentation]: location of binaries not as described

### ISSUE THREAD

**Issue by NiloCK** [trailofbits/solc-select#169]
### Describe the issue:

From the readme:

> The downloaded binaries are stored in `~/.solc-select/artifacts/`.

From my console (Ubuntu) after the quick-start `pip3 install solc-select`:

![image](https://user-images.githubusercontent.com/10780590/225939751-4f786d2b-4840-4a24-9e65-72349cabe0d4.png)

### Code example to reproduce the issue:

(not a code issue)

### Version:

This doesn't seem to work. The version is current - just ran quick start.

![image](https://user-images.githubusercontent.com/10780590/225942101-b83ddb23-2986-4794-89a0-1f8e1ec635ac.png)

![image](https://user-images.githubusercontent.com/10780590/225940256-97ffb342-507b-49a7-8b93-b45f7bf32954.png)

**Comment by elopez** [comment]
Hi! just to clarify, `solc-select` itself (i.e. the `solc` and `solc-select` executables) is installed wherever `pip` installs Python programs in your system. The solc binaries downloaded by `solc-select` (i.e. the ones you get when you run `solc-select install 0.8.10` for example) are stored in `~/.solc-select/artifacts/`

**Comment by NiloCK** [comment]
Excellent, thanks. I was hitting issues related to prior solc installations, so I starting looking for "what was where" and found something that didn't jar with my first reading of the readme.

I understand the readme's comment now :)

Feel free to close, or maybe something like

> The versioned `solc` binaries are stored in `~/.solc-select/artifacts/`.

could be a little clearer about what's stored in there.

**Comment by 0xicingdeath** [comment]
Edited in most recent PR – thanks @NiloCK  (and @elopez) :)
