### ISSUE TITLE
Creating Local Contexts With Solc-select

### ISSUE THREAD

**Issue by Akshat-Mishra101** [trailofbits/solc-select#171]
# solc-select and slither multithreaded parallel execution

Is there a way to create a local solc version context for slither? 

I've made a small tool which takes a smart contract, and passes it through slither to execute a few tests. Now i want to scale this app, and want it to be able to handle multiple requests per second. For this, I've been using threads but the solc-select <version> changes the globl context, which is now shared across all threads. 

is there any workaround?

**Comment by elopez** [comment]
Hi! An option would be to set the `SOLC_VERSION` environment variable. This variable takes precedence over the global solc-select context. This way you can avoid calling `solc-select use ...`

```
% solc --version
solc, the solidity compiler commandline interface
Version: 0.8.19+commit.7dd6d404.Darwin.appleclang
% export SOLC_VERSION=0.8.0
% solc --version           
solc, the solidity compiler commandline interface
Version: 0.8.0+commit.c7dfd78e.Darwin.appleclang
```

**Comment by Akshat-Mishra101** [comment]
Hey @elopez, thanks for the swift reply :). I'm wondering if it would work with a command like "export SOLC_VERSION=0.8.0; slither ."

**Comment by elopez** [comment]
on most shells you can do `SOLC_VERSION=0.8.0 slither foo.sol` and it should work 👍  If you are doing it programmaticaly, most languages also offer a way to add or update an environment variable for a command execution, like [on Go](https://stackoverflow.com/a/41133244) or [Python](https://www.scivision.dev/python-calling-python-subprocess/)

**Comment by Akshat-Mishra101** [comment]
Thank you so much for the help @elopez, I'm using nodejs with child processes to achieve this.

**Comment by elopez** [comment]
[Something like this](https://stackoverflow.com/a/67059161) should work for node, see how `FOO` is added.

**Comment by Akshat-Mishra101** [comment]
amazing, this works. Thanks for the help man, Ill close this thread.
