### ISSUE TITLE
[Bug-Candidate]:  make like goup or fnm to static binary file

### ISSUE THREAD

**Issue by newyorkthink** [trailofbits/solc-select#173]
### Describe the issue:

goup and fnm version manager is static binary file
it not to install pip3
i can it to pull /usr/bin/ to run

### Code example to reproduce the issue:

binary file

### Version:

binary file

**Comment by elopez** [comment]
Hi! solc-select is written in Python so you'll need Python to run it. pip3 usually comes bundled with Python.
