### ISSUE TITLE
Feature request: install and automatically switch to the newly installed version

### ISSUE THREAD

**Issue by damilolaedwards** [trailofbits/solc-select#178]
Currently, to use an uninstalled version of solc-select, it requires to separate steps, running `solc-select install <version>` then `solc-select use <version>`. There should be a flag to installs and switches to the newly installed version automatically thereby merging the two separate commands into one.

**Comment by 0xalpharush** [comment]
Does the existing flag `solc-select use <version> --always-install` accomplish what you describe or you mean something different?
