### ISSUE TITLE
[Bug-Candidate]: 

### ISSUE THREAD

**Issue by goheesheng** [trailofbits/solc-select#214]
### Describe the issue:

Unable to compile contracts or libraries for contracts ^0.8.20,

### Code example to reproduce the issue:

forge test or forge build

### Version:

0.8.24 and 0.8.27 both also cause this issue

### Relevant log output:

```shell
Encountered invalid solc version in lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/proxy/ERC1967/ERC1967Utils.sol: No solc version exists that matches the version requirement: ^0.8.21
```

**Comment by elopez** [comment]
Hi! Judging by the error message and your description, this seems to be an error from foundry, and therefore you are probably not using solc-select. You can try upgrading your foundry installation by running `foundryup` and see if that fixes the problem.

**Comment by goheesheng** [comment]
Yup thanks
