### ISSUE TITLE
Automatically change solc version depending on pragma 

### ISSUE THREAD

**Issue by 0xicingdeath** [trailofbits/solc-select#61]
When running `solc <file>` currently, users have to change the solc-select global version, then run the solc file: 
```bash 
solc-select install <version> 
solc-select use <version> 
solc <file to execute> 
```

Example file: 
```solidity
pragma solidity 0.4.15;
contract Foo {
        function Foo() {
        }
}
```

When changing the pragma, it requires users to run the `solc-select use <version>` in their terminal to use the correct solc version. It would speed up testing significantly if the tool had the ability to change the version automatically.

**Comment by 0xicingdeath** [comment]
Closing, as this is something that crytic-compile does.

**Comment by TalbenXu** [comment]
Hi, @0xicingdeath ,

I am currently try to using slither to detect different version solidity contract in a folder, and everytime I need to use solc-select to choose the right version before running the slither. And how could I use crytic-compile to auto select right solc version based on pragma on contract. It will be extremely helpful to test on batch for me.

Thank you
