### ISSUE TITLE
Commands to change global Solc --version do not work on Arch Linux

### ISSUE THREAD

**Issue by daweth** [trailofbits/solc-select#72]
`solc-select use 0.7.6`
and 
`SOLC_VERSION=0.7.6`

do not change the result of 

`solc --version`

**Comment by 0xicingdeath** [comment]
Hey @daweth, this usually happens if you have another version of `solc` installed on your machine. Can you share the output of `which solc`?

**Comment by daweth** [comment]
`/home/me/.nix-profile/bin/solc`

Ah, seems like I have this from Nix (dapptools maybe?)

How would I change to a different solc directory?

**Comment by arcz** [comment]
@daweth what does your $PATH look like? If you used system Python to install `solc-select` then most probably `~/.nix-profile/bin/` takes precedence over the Python executables path. I don't know what do you want to achieve but if you have Nix installed already you can try `solc-select` in nix-shell with `nix-shell -p python3Packages.solc-select`.

**Comment by 0xicingdeath** [comment]
Hey @daweth, we're closing this issue as @arcz provided fixes for the Python path. Please reopen or create a new issue if you experience this again. Thanks!
