### ISSUE TITLE
how to install solc-select ?

### ISSUE THREAD

**Issue by simin98** [trailofbits/solc-select#75]
![image](https://user-images.githubusercontent.com/83910332/138382637-e1081e82-40ba-46a4-8180-96352ca2b2c2.png)
pip install solc-select==0.2.0
pip install solc-select==0.2.1
Could not find a version that satisfies the requirement solc-select==0.2.1 (from versions: )
No matching distribution found for solc-select==0.2.1
![image](https://user-images.githubusercontent.com/83910332/138382982-c7bc2b49-97bc-4b38-a61a-76461a6abd87.png)
ang my  python version is 2.7

when I try 
git clone https://github.com/crytic/solc-select.git
./solc-select/scripts/install.sh

it shows 
bash: ./solc-select/scripts/install.sh: No such file or directory

so how can I do ?

**Comment by 0xicingdeath** [comment]
Hey @simin98! Thanks for reporting this. Do you have `python3` installed? I think you might need Python 3.x for this, as Python 2 has been deprecated. 

The `install.sh` file you're mentioning is part of an older release of solc-select that uses Docker. This has since been refactored in Python. Do you know where you saw these instructions? 

You can try the following instead. (You can do this _or_ the installation via pip): 
```
git clone https://github.com/crytic/solc-select.git
cd solc-select
python3 setup.py install 
```

**Comment by simin98** [comment]
> Hey @simin98! Thanks for reporting this. Do you have `python3` installed? I think you might need Python 3.x for this, as Python 2 has been deprecated.
> 
> The `install.sh` file you're mentioning is part of an older release of solc-select that uses Docker. This has since been refactored in Python. Do you know where you saw these instructions?
> 
> You can try the following instead. (You can do this _or_ the installation via pip):
> 
> ```
> git clone https://github.com/crytic/solc-select.git
> cd solc-select
> python3 setup.py install 
> ```

I tried it but it do not work.
I want to use oyente(the Smart Contract Detection Tool),and its default environment is python 2.7.when i switched python version (2.7to 3.6),i can not use pip3.
==

**Comment by 0xicingdeath** [comment]
Hi @simin98! Python2 isn't officially supported anymore, which is why solc-select will not work on that setup. You may need to raise this issue in Oyente which is relying on an older version.

**Comment by rahulEth** [comment]
@simin98 
use Python 3.8
then 
git clone https://github.com/crytic/solc-select.git
cd solc-select
sudo python3 setup.py install

**Comment by elopez** [comment]
Closing this issue as it has not had activity for a while. If you are still experiencing issues on the latest release feel free to create a new issue.
