### ISSUE TITLE
Windows Port

### ISSUE THREAD

**Issue by wokring** [trailofbits/solc-select#76]
I have installed the package through a git clone as mentioned in [#43](https://github.com/crytic/solc-select/issues/43) through pip installation. Installation of solc compilers is fine but I can't actually compile anything. Is it a bug on my end by installing through pip instead of a manual install through setup.py?

**Comment by 0xicingdeath** [comment]
Hey @Zernoxi! The windows feature isn't available through pip yet – you can give the manual install through `setup.py` instead. (You'll want to uninstall the pip3 version). After cloning, you can run `python3 setup.py install`. Let me know if that works?

**Comment by wokring** [comment]
@NatalieChin80 Sorry if I wasn't specific enough. I cloned the the `add\windows-support` branch then I installed it through `pip` as from my understanding, `pip` can install local repositories and will also call `setup.py`. Or is there something with `pip` that is different from directly installing through `setup.py`?

**Comment by wokring** [comment]
> Hey @Zernoxi! The windows feature isn't available through pip yet – you can give the manual install through `setup.py` instead. (You'll want to uninstall the pip3 version). After cloning, you can run `python3 setup.py install`. Let me know if that works?

@NatalieChin80 I have just tried with `setup.py` but it only installs the solc compiler and when I run `solc -o <file>.sol` it doesn't output anything. Is this intended for now?

EDIT 1 (Nov 11 2021):
Never mind, it just doesn't have a help section for now and requires an output type and path. I just thought that it would show a successful/unsuccessful compilation message.

**Comment by 0xicingdeath** [comment]
Hey @Zernoxi! Just seeing your edit – do you mean that running it with the `-o` flag should provide errors when it doesn't?  Once you provide the output type and path, do you get the expected output?

**Comment by wokring** [comment]
@NatalieChin80 Yeah, once I provide the output type and path, I do get the expected output. But was expecting a compilation message like in the video linked here: https://www.youtube.com/watch?v=zUpbZRmITZQ&list=WL&index=37&t=135s
