### ISSUE TITLE
win

### ISSUE THREAD

**Issue by 161424** [trailofbits/solc-select#92]
When I use pip to install in windows, I encounter that the python platform does not have "sys. Platform = =" win * ", and" platform = uppercase platform ". It seems that I am not too good here. Moreover, will it be useful to mention" emscripten - wasm32 "in the manual?

**Comment by 0xicingdeath** [comment]
Hey @161424! Can you share the terminal output that you get from running? It's not fully clear to me what the error is. 

I'm also not entirely sure what you mean by `emscripten - wasm32`?

**Comment by 161424** [comment]
In line 222 of your solc-select.py file, I need to change it to lowercase to download it correctly, otherwise it is "unsupported platform". "Emscripten - wasm32" in https://docs.soliditylang.org/en/latest/installing-solidity.html#static -Binaries' warning is described

**Comment by 161424** [comment]
Sorry, it's my problem. I installed it using pip. Maybe the package management of Python platform has not been updated, which leads to a problem. Now the problems are solved for the packages obtained directly using GIT

**Comment by 0xicingdeath** [comment]
If you want to use through pip, I believe you would need to run it through `pip install solc-select==1.0.0b1` to get the beta release. 

Closing this as it seems resolved – feel free to re-open or open a new issue if you are still experiencing problems.
