### ISSUE TITLE
Unsupported platform

### ISSUE THREAD

**Issue by zerox-me** [trailofbits/solc-select#93]
I am trying to run "Slither" program but failed. The error is like this.
"Solidity version not found: No solc version set. Run `solc-select use VERSION` or set SOLC_VERSION environment variable."
But I cannot set solc version using "solc-select". It always show "Unspported platform".

![image](https://user-images.githubusercontent.com/59189994/157859169-3866c1f5-1aa6-49e5-bf37-1840706e0d35.png)

**Comment by 0xicingdeath** [comment]
Hey @mstrong-tech, can you share a bit more about your setup? 

Are you on Windows? It seems you also cloned solc-select. Did you run `python3 setup.py develop`?

**Comment by 0xAppo** [comment]
Hi, I'm on Windows and having similar issues, I ran the setup.py develop script but still receiving the "Unsupported Platform" error. Any tips? Thanks.

**Comment by deep-quality-dev** [comment]
Hi, I've got similar issues on Mac, also tested with setup.py, returning `Unspported Platform` as above image.
Thank you for community.

**Comment by 0xicingdeath** [comment]
Hey @0xAppo, thanks for reporting this issue. Can you provide a bit more information on your system? It seems you cloned it – what branch are you on in the repo? 

Hey @deep-quality-dev, thanks for reporting! This is the first I've seen it not being supported on Mac... what OS are you on?

**Comment by calnix** [comment]
Facing a similar issue as @0xAppo. 
![image](https://user-images.githubusercontent.com/22549197/171971633-2836487b-7f62-42ec-bf9a-7ee26c5cd6d9.png)

I'm running win10 64bit with python 3.9.10. 
Do let me know if you need any other particulars regarding my system.

Thank you.

**Comment by 0xicingdeath** [comment]
Hey @calnix , thanks for reporting. 

Can you try uninstalling `solc-select` and running `pip install solc-select==1.0.0b1` or running the `setup.py` from the `dev` branch on this repo?

**Comment by calnix** [comment]
@NatalieChin80 Yes mam, it works beautifully. 

![image](https://user-images.githubusercontent.com/22549197/172074831-370a4621-90f9-47de-93b6-711b3fa94536.png)
Thank you!

**Comment by iaskgithub** [comment]
@NatalieChin80   it works beautifully,thank you

**Comment by 0xicingdeath** [comment]
Happy to help! I'm going to close this issue. Please open a new issue if you experience something else!
