### ISSUE TITLE
Specify path to solc

### ISSUE THREAD

**Issue by alloc33** [trailofbits/solc-select#99]
Is there any way to specify path to 'solc' executalbe? I want to use LSP (solc) inside neovim, neovim provides it's own solc installation to it's own path.

**Comment by elopez** [comment]
Hi! If you want to use an external solc binary you can do so directly, you don't need solc-select in that case. Just make sure it's first in `PATH`. I'll close the issue but feel free to reply back if I'm misunderstanding here.
